version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://cache
      - JWT_SECRET=53cr3t
    volumes:
      # - .:/usr/src/app
      - ./src/db/development.sqlite:/usr/src/app/src/db/development.sqlite
    links:
      - redis
      
    command: ["yarn", "run", "start"]
    # depends_on:
    #   - db
  # db:
  #   image: bitnami/sqlite
  #   volumes:
  #     - sqlite-data:/var/lib/sqlite
# volumes:
#   sqlite-data:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
